LOCAL_DISTANCE = 16.0
LOCAL_MAP_DIM = 8.0
ACCURACY_THRESHOLD = 0.6

ACCURACY_THRESHOLD_PREDICTION = 0.5

# grid out map n*n n is
GRID_LENGTH = 5

# laser fov in degree
LASER_FOV = 270.0
MAX_RANGE_LASER = 18.0

POINT_LIFE_TIME = 30